# Generated by Django 4.1.2 on 2022-11-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar'),
            preserve_default=False,
        ),
    ]
