# Generated by Django 4.1.2 on 2022-12-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_remove_customuser_phone_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
