# Generated by Django 4.1.2 on 2022-12-04 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998********'. Up to 15 digits allowed.", regex='^\\+?998?\\d{12}$')]),
        ),
    ]
