# Generated by Django 4.1.2 on 2022-11-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='data',
            new_name='data_order',
        ),
    ]
