# Generated by Django 4.1.2 on 2022-11-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0002_rename_data_orderproduct_data_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='display_resolution',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='display_size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='platform_os',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='selfie_vamera',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
