# Generated by Django 4.1.2 on 2022-11-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0003_product_battery_type_product_display_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='platform_os',
        ),
    ]
