# Generated by Django 4.1.2 on 2022-11-10 19:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0004_remove_product_platform_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='instructions_image_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=''), blank=True, default=list, null=True, size=15),
        ),
    ]
