# Generated by Django 4.1.2 on 2022-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0008_remove_product_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo'),
            preserve_default=False,
        ),
    ]
